spring:
  application:
    name: techinnovate
  profiles:
    active: @activatedProperties@
  #    active: test
  datasource:
#    url: jdbc:mysql://10.80.18.59:3306/tech_innovate?characterEncoding=UTF-8&nullCatalogMeansCurrent=true&&createDatabaseIfNotExist=true
#    username: root
#    password: szjj123
#    schema: classpath:db/schema.sql
#    data: classpath:db/data.sql
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      #连接池配置
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 100000
      ###监控配置 begin###
      web-stat-filter:
        # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
        enabled: true
        url-pattern: "/druid/*"
        reset-enable: false
        login-username: admin
        login-password: 123456
        allow: 127.0.0.1
      ###监控配置 end###
      filter:
        # 配置StatFilter
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 5000
        # 配置WallFilter
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: true
            drop-table-allow: false

  #    driver-class-name: com.mysql.cj.jdbc.Driver
##    schema: classpath:db/schema.sql
##    data: classpath:db/data.sql
#
#    url: jdbc:mysql://127.0.0.1:3306/test15?characterEncoding=UTF-8&nullCatalogMeansCurrent=true&&createDatabaseIfNotExist=true
#    username: root
#    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  servlet.multipart:
    max-file-size: 104857600
    max-request-size: 104857600
server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
  client:
    service-url:
      defaultZone: http://hc:hc123@eureka.default.svc.cluster.local/eureka/
#      defaultZone: http://hc:hc123@eureka.cosmic.com/eureka/
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
mybatis:
  table:
    auto: update
flowable:
  #关闭定时任务JOB
  async-executor-activate: false
  #  将databaseSchemaUpdate设置为true。当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本。
  database-schema-update: false
