eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    server.waitTimeInMsWhenSyncEmpty: 0
logging.level:
  com.howie.shiro.mapper: DEBUG
  # 控制台日志输出级别
  org.springframework.web: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itais?characterEncoding=UTF-8&nullCatalogMeansCurrent=true&&createDatabaseIfNotExist=true&&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  redis:
    database: 1
    host: localhost
    password: 123456
    port: 6379
minio:
  url: http://localhost:9000
  accessKey: admin
  secretKey: 123456
  bucketName: test